//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymlinkSwapper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymlinkSwapper.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string Default_Header {
            get {
                return ResourceManager.GetString("Default_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured.
        /// </summary>
        internal static string Default_Message {
            get {
                return ResourceManager.GetString("Default_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR CREATING SYMLINK.
        /// </summary>
        internal static string FailedToCreateSymlinkException_Header {
            get {
                return ResourceManager.GetString("FailedToCreateSymlinkException_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symlink could not be created.
        ///Unknown issue..
        /// </summary>
        internal static string FailedToCreateSymlinkException_Message {
            get {
                return ResourceManager.GetString("FailedToCreateSymlinkException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO FILES TO CYCLE THROUGH.
        /// </summary>
        internal static string NoFilesException_Header {
            get {
                return ResourceManager.GetString("NoFilesException_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory containing at least two files..
        /// </summary>
        internal static string NoFilesException_Message {
            get {
                return ResourceManager.GetString("NoFilesException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSUFFICIENT USER RIGHTS.
        /// </summary>
        internal static string PriviligeNotHeldException_Header {
            get {
                return ResourceManager.GetString("PriviligeNotHeldException_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as admin or configure current user rights:
        ///1. Go to &apos;Start&apos; &gt; &apos;Run&apos; and enter secpol.msc. Then click OK.
        ///2. In the Local Security Policy window that opens, go to Security Settings &gt; Local Policies &gt; User Rights Assignment.
        ///3. In the list, find the &apos;Create symbolic links&apos; item and double-click it. Add yourself/the required user/the whole users group to the list..
        /// </summary>
        internal static string PriviligeNotHeldException_Message {
            get {
                return ResourceManager.GetString("PriviligeNotHeldException_Message", resourceCulture);
            }
        }
    }
}
